### ISSUE TITLE
Error in command `atlas-placement-hints  isocortex`

### ISSUE THREAD

**Issue by lecriste** [BlueBrain/atlas-placement-hints#25]
I noticed that the latest version of the code (v0.1.3) fails at generating isocortex PHs with

```
Traceback (most recent call last):
  File "/usr/local/bin/atlas-placement-hints", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/atlas_placement_hints/app/cli.py", line 18, in cli
    app()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/atlas_commons/app_utils.py", line 47, in wrapper
    function(*args, **kw)
  File "/usr/local/lib/python3.10/site-packages/atlas_placement_hints/app/placement_hints.py", line 278, in isocortex
    _placement_hints(
  File "/usr/local/lib/python3.10/site-packages/atlas_placement_hints/app/placement_hints.py", line 108, in _placement_hints
    distances_info, problems = compute_placement_hints(
  File "/usr/local/lib/python3.10/site-packages/atlas_placement_hints/compute_placement_hints.py", line 73, in compute_placement_hints
    distances_info = atlas.compute_distances_to_layer_boundaries(
TypeError: VoxelBasedLayeredAtlas.compute_distances_to_layer_boundaries() got an unexpected keyword argument 'thalamus_meshes_dir'

```
The command I executed is
```
atlas-placement-hints  isocortex  --hierarchy-path hierarchy_ccfv3_l23split_barrelsplit.json  --annotation-path annotation_ccfv3_l23split_barrelsplit_validated.nrrd  --metadata-path isocortex_metadata.json   --direction-vectors-path direction_vectors/direction_vectors_ccfv3.nrrd   --algorithm voxel-based  --output-dir placement_hints
```
with input files from
`/gpfs/bbp.cscs.ch/data/project/proj84/atlas_pipeline_runs/v1.0.1_prod/`

**Comment by asoplata** [comment]
Found and fixed the issue, currently testing fix
